// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAipCL6gCxsorY_FpOReUQ95OBfAfNcCQU',
    appId: '1:593949371445:web:0ef83299114c8d1056957c',
    messagingSenderId: '593949371445',
    projectId: 'flutter-lat',
    authDomain: 'flutter-lat.firebaseapp.com',
    storageBucket: 'flutter-lat.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIzlFki6vYMLKYs3_P5C4aIGYJ3RuqMp8',
    appId: '1:593949371445:android:57d23960a062b94356957c',
    messagingSenderId: '593949371445',
    projectId: 'flutter-lat',
    storageBucket: 'flutter-lat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwm_-1KrUWV5uvJ70pmaC0mkZ0F1M-8vE',
    appId: '1:593949371445:ios:860329e088307d2656957c',
    messagingSenderId: '593949371445',
    projectId: 'flutter-lat',
    storageBucket: 'flutter-lat.firebasestorage.app',
    iosBundleId: 'com.example.appfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwm_-1KrUWV5uvJ70pmaC0mkZ0F1M-8vE',
    appId: '1:593949371445:ios:860329e088307d2656957c',
    messagingSenderId: '593949371445',
    projectId: 'flutter-lat',
    storageBucket: 'flutter-lat.firebasestorage.app',
    iosBundleId: 'com.example.appfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0hW5Mqe4bfLa26_v4wDmTbyenw-GOWic',
    appId: '1:593949371445:web:02e06b2534136f2156957c',
    messagingSenderId: '593949371445',
    projectId: 'flutter-lat',
    authDomain: 'flutter-lat.firebaseapp.com',
    storageBucket: 'flutter-lat.firebasestorage.app',
  );
}
